class CountryNameLocalizer {
  final Map<String, Map<String, String>> _countryMap = {
    "vi": {
      "af": "Afghanistan",
      "al": "Albania",
      "dz": "Algérie",
      "ad": "Andorra",
      "ao": "Angola",
      "ag": "Antigua và Barbuda",
      "ar": "Argentina",
      "am": "Armenia",
      "au": "Úc",
      "at": "Áo",
      "az": "Azerbaijan",
      "bs": "Bahamas",
      "bh": "Bahrain",
      "bd": "Bangladesh",
      "bb": "Barbados",
      "by": "Belarus",
      "be": "Bỉ",
      "bz": "Belize",
      "bj": "Bénin",
      "bt": "Bhutan",
      "bo": "Bolivia",
      "ba": "Bosna và Hercegovina",
      "bw": "Botswana",
      "br": "Brazil",
      "bn": "Brunei",
      "bg": "Bulgaria",
      "bf": "Burkina Faso",
      "bi": "Burundi",
      "kh": "Campuchia",
      "cm": "Cameroon",
      "ca": "Canada",
      "cv": "Cabo Verde",
      "cf": "Cộng hòa Trung Phi",
      "td": "Chad",
      "cl": "Chile",
      "cn": "Trung Quốc",
      "co": "Colombia",
      "km": "Comoros",
      "cr": "Costa Rica",
      "ci": "Bờ Biển Ngà",
      "hr": "Croatia",
      "cu": "Cuba",
      "cy": "Síp",
      "cz": "Cộng hòa Séc",
      "cd": "Cộng hòa Dân chủ Congo",
      "dk": "Đan Mạch",
      "dj": "Djibouti",
      "dm": "Dominica",
      "do": "Cộng hòa Dominica",
      "ec": "Ecuador",
      "eg": "Ai Cập",
      "sv": "El Salvador",
      "gq": "Guinea Xích Đạo",
      "er": "Eritrea",
      "ee": "Estonia",
      "et": "Ethiopia",
      "fj": "Fiji",
      "fi": "Phần Lan",
      "fr": "Pháp",
      "ga": "Gabon",
      "gm": "Gambia",
      "ge": "Gruzia",
      "de": "Đức",
      "gh": "Ghana",
      "gr": "Hy Lạp",
      "gd": "Grenada",
      "gt": "Guatemala",
      "gn": "Guinea",
      "gw": "Guinea-Bissau",
      "gy": "Guyana",
      "ht": "Haiti",
      "hn": "Honduras",
      "hu": "Hungary",
      "is": "Iceland",
      "in": "Ấn Độ",
      "id": "Indonesia",
      "ir": "Iran",
      "iq": "Iraq",
      "ie": "Ai-len",
      "il": "Israel",
      "it": "Ý",
      "jm": "Jamaica",
      "jp": "Nhật Bản",
      "jo": "Jordan",
      "kz": "Kazakhstan",
      "ke": "Kenya",
      "ki": "Kiribati",
      "kp": "Bắc Triều Tiên",
      "kr": "Hàn Quốc",
      "kw": "Kuwait",
      "kg": "Kyrgyzstan",
      "la": "Lào",
      "lv": "Latvia",
      "lb": "Liban",
      "ls": "Lesotho",
      "lr": "Liberia",
      "ly": "Libya",
      "li": "Liechtenstein",
      "lt": "Litva",
      "lu": "Luxembourg",
      "mg": "Madagascar",
      "mw": "Malawi",
      "my": "Malaysia",
      "mv": "Maldives",
      "ml": "Mali",
      "mt": "Malta",
      "mh": "Quần đảo Marshall",
      "mr": "Mauritania",
      "mu": "Mauritius",
      "mx": "Mexico",
      "fm": "Micronesia",
      "md": "Moldova",
      "mc": "Monaco",
      "mn": "Mông Cổ",
      "me": "Montenegro",
      "ma": "Morocco",
      "mz": "Mozambique",
      "mm": "Myanmar",
      "na": "Namibia",
      "nr": "Nauru",
      "np": "Nepal",
      "nl": "Hà Lan",
      "nz": "New Zealand",
      "ni": "Nicaragua",
      "ne": "Niger",
      "ng": "Nigeria",
      "mk": "Cộng hòa Bắc Macedonia",
      "no": "Na Uy",
      "om": "Oman",
      "pk": "Pakistan",
      "pw": "Palau",
      "pa": "Panama",
      "pg": "Papua New Guinea",
      "py": "Paraguay",
      "pe": "Peru",
      "ph": "Philippines",
      "pl": "Ba Lan",
      "pt": "Bồ Đào Nha",
      "qa": "Qatar",
      "ro": "Romania",
      "ru": "Nga",
      "rw": "Rwanda",
      "kn": "Saint Kitts và Nevis",
      "lc": "Saint Lucia",
      "vc": "Saint Vincent và Grenadines",
      "ws": "Samoa",
      "sm": "San Marino",
      "st": "São Tomé và Príncipe",
      "sa": "Ả Rập Saudi",
      "sn": "Senegal",
      "rs": "Serbia",
      "sc": "Seychelles",
      "sl": "Sierra Leone",
      "sg": "Singapore",
      "sk": "Slovakia",
      "si": "Slovenia",
      "sb": "Quần đảo Solomon",
      "so": "Somalia",
      "za": "Nam Phi",
      "es": "Tây Ban Nha",
      "lk": "Sri Lanka",
      "sd": "Sudan",
      "sr": "Suriname",
      "se": "Thụy Điển",
      "ch": "Thụy Sĩ",
      "sy": "Syria",
      "tj": "Tajikistan",
      "tz": "Tanzania",
      "th": "Thái Lan",
      "tl": "Timor-Leste",
      "tg": "Togo",
      "to": "Tonga",
      "tt": "Trinidad và Tobago",
      "tn": "Tunisia",
      "tr": "Thổ Nhĩ Kỳ",
      "tm": "Turkmenistan",
      "tv": "Tuvalu",
      "ug": "Uganda",
      "ua": "Ukraina",
      "ae": "Các Tiểu Vương Quốc Ả Rập Thống Nhất",
      "gb": "Vương quốc Anh",
      "us": "Hoa Kỳ",
      "uy": "Uruguay",
      "uz": "Uzbekistan",
      "vu": "Vanuatu",
      "ve": "Venezuela",
      "vn": "Việt Nam",
      "ye": "Yemen",
      "zm": "Zambia",
      "zw": "Zimbabwe"
    },

  };

  String? getCountryName(String code, String locale) {
    return _countryMap[code]?[locale] ?? _countryMap[code]?['en'];
  }
}
